### ISSUE TITLE
The Hack doesnt work

### ISSUE THREAD

**Issue by frehall** [wuseman/TG799VAC-XTREME-17.2-MINT#9]
The exploit used here is closed. I was too slacky to close Telias access to my router so they were still able to update and remove this backdoor to root.

I bet there will be no new solution until Mr. Wuseman has bricked his router and ordered a new one. :)

**Comment by LuKePicci** [comment]
Rule of thumb: if it was rooted, it can be rooted again. Are you talking about VBNT-H?

Please tell me the exact firmware version. I need the full version string xx.x.xxxx-**xxxxxx**

You can downgrade to previous exploitable version and get in again. Once you are back in, I will ask you to download the new locked-down firmware image.

**Comment by wuseman** [comment]
Some are -H and some are -W and some are -R it seems.

17.2.0405-1441010-20181017112915 is current for VBNT-W

**Comment by LuKePicci** [comment]
-R is VANT-R, TG799vac "Trådlös router"
![image](https://user-images.githubusercontent.com/8722358/65331747-aaa8c580-dbbd-11e9-8c2a-6f60d4ea37f9.png)
![image](https://user-images.githubusercontent.com/8722358/65331766-b5635a80-dbbd-11e9-99ef-a51331e92518.png)
![image](https://user-images.githubusercontent.com/8722358/65333278-7f73a580-dbc0-11e9-8293-da668ab4f8c3.png)

The only tch board from telia (well, recent enough) which is still out of my radars is this one "Wifi-router"
![image](https://user-images.githubusercontent.com/8722358/65333569-09bc0980-dbc1-11e9-8ac6-b5c41042f1ef.png)
![image](https://user-images.githubusercontent.com/8722358/65331690-8d73f700-dbbd-11e9-9ade-ce10318bc174.png)
![image](https://user-images.githubusercontent.com/8722358/65333698-3ff98900-dbc1-11e9-87aa-f88c0f1d018a.png)

-H is VBNT-H, TG799vac Xtream "Wifi-router Plus" (subject of this repo)
![image](https://user-images.githubusercontent.com/8722358/65331928-fce9e680-dbbd-11e9-9e74-8194becd3517.png)
![image](https://user-images.githubusercontent.com/8722358/65332023-328ecf80-dbbe-11e9-9415-8521cbba6023.png)
![image](https://user-images.githubusercontent.com/8722358/65333802-720aeb00-dbc1-11e9-9b88-2ab75813e543.png)
![image](https://user-images.githubusercontent.com/8722358/65332050-3b7fa100-dbbe-11e9-8790-84ce8495ffff.png)

-W is unknown to me, but if you see it somewhere maybe it was just the family ancestor name. Each board belongs to a family of similar boards sharing the same sources. The source package gets named as the main family member. and sometimes you see it appearing somewhere else by mistake. Did you really saw some --W device from Telia? Is it that second one I mentioned above?

**Comment by wuseman** [comment]
yeah, thanks alot for this explanation

W is same as H it seems. Yes, it's from telia.

![Screenshot](https://nr1.nu/f/cnc.png)

### From Syslog
Sep 20 16:55:17 | daemon.info | dnsmasq-dhcp[4571] | DHCPACK(br-lan) 192.168.1.69 TG799TSvacXtream-AP-B57372
-- | -- | -- | --

**Comment by wuseman** [comment]
BUT, in /etc/boards on VBNT-H (my old one, i did a mirror before it got bricked) then I see the folders on the pictures.

But VANT-W and VBNT-H is identical it seems, no idea why I have W, but i seen some others that also have W instead of H, really confusing.

But if check in etc/boards then I see 3 folders, all are empty:

![Screenshot](https://nr1.nu/f/verb.png)

**Comment by frehall** [comment]
Ive got the white one. But mine is named 'V3' in the end. 'Telia WiFi-router Plus V3'

![dickpick9](https://user-images.githubusercontent.com/54959205/65339277-1eea6580-dbcc-11e9-80c3-35ec90370842.jpg)

Btw, How do you downgrade?

**Comment by wuseman** [comment]
Another funny thing is if I browsing to the wireless-modal then I see radius passwords and secrets, what is this for?

![Screenshot](https://nr1.nu/f/ggjd.png)

Another bug I found is this:

When you browse to http://192.168.1.1/modals/wireless-modal.lp it looks like above, when i browsing to: http://192.168.1.1/modals/wireless-modal.lp?radio=radio_2G&iface=mgmt&action=reboot instead I trying everything then I get comehem as SSID? How crazy?

**Comment by LuKePicci** [comment]
> Ive got the white one. But mine is named 'V3' in the end. 'Telia WiFi-router Plus V3'

HAHA YOU GOT IT! let me update my previous summary

This is my small list of known Telia firmwares, those one marked with * are only supposed to be valid links as I have no more access to Telia network to get on my own.

```
http://131.116.22.230/15516436o1361004closed.rbi VDNT-O
http://131.116.22.230/15516436o1361005closed.rbi VDNT-O

http://131.116.22.230/15516436r1361003closed.rbi VANT-R *
http://131.116.22.230/1627732r2221004closed.rbi VANT-R
http://131.116.22.230/172339r1021008closed.rbi	VANT-R
http://131.116.22.230/172339r1021022closed.rbi	VANT-R

http://131.116.22.230/1627732w2221002closed.rbi VANT-W *

http://131.116.22.230/172339h1441018closed.rbi VBNT-H
http://131.116.22.230/172405h1441008closed.rbi VBNT-H *
```

> Btw, How do you downgrade?

Follow Type 3 instructions https://hack-technicolor.readthedocs.io/en/latest
By 50% chances it will be damn east, by the other 50% it will be quite difficult but **never impossible**.


> All 3 folders are empty, but there is no config directory for VANT-W

They are all part of the same family, now we only need to know if VANT-W really existed or it was just a leftover to show VANT-W in device details. The mistery above the second device of the list is still there

> I see radius passwords and secrets, what is this for?

It depends, usually you see such implementations for Community WiFi services or something else. Random data gets filled in by individual device eripv2 contents, so you arre probably seeing some default wpa2-enterprise passwords, as like as you see default wep and wpa2-personal passwords.

**Comment by frehall** [comment]
Hmm, damn. That seems to be quite some hassle to get in there again... Compared to the dyndns-menu way.

I just want in there so I can get a hang of the network setup. Would like to setup my own OpenWRT box with IPTV support and ditch the Telia router.

**Comment by LuKePicci** [comment]
Just try the BOOTP flashing, if you are on bank_1 already (it changes active bank on each upgrade) you will see it immediately downgraded.

**Comment by frehall** [comment]
Hmm, could or would a successful attempt benefit you in any way?
If not, ill have to dig deep to find the motivation to hassle around with this heh

**Comment by LuKePicci** [comment]
Not me for sure.. We've got almost everything we need for your model, however if you manage to get in again you will be capable of downloading the firmwares we are missing, including your current one, so @wuseman could look into it for easier exploits.

**Comment by frehall** [comment]
the torrent with the .rbi file seems to be dead anyway

**Comment by LuKePicci** [comment]
Now seeding from home. I'm sorry I still have to move some firmwares to a permanent seedbox.

**Comment by frehall** [comment]
Ok, cool. Got it. Is there a irc-server or something about this?

**Comment by LuKePicci** [comment]
You can write on the github repo of the wiki I linked before. https://github.com/kevdagoat/hack-technicolor

**Comment by kevdagoat** [comment]
I should setup one :)

**Comment by wuseman** [comment]
The problem is that we can't download the rbi files, or atleast I cant. 

Here is syslog from a default reset I just did, maybe you can help me figure out how I can download the rbi files for W model:

https://nr1.nu/f/nirkm

**Comment by LuKePicci** [comment]
I told you already. The fileserver is reachable on the mgmt vlan only. Of course the telia gateways are already configured for such an access, this means if you just do wget http//…./file.rbi from inside the gateway it will just work. You can do the same by directly connecting your pc or any other configurable router to do the same.

**Comment by LuKePicci** [comment]
@wuseman I sent you a private message via telegram

**Comment by wuseman** [comment]
Cool, been busy I reply you there. Cheers

**Comment by wuseman** [comment]
Is it default to have GBNT-G  VANT-4  VANT-6  VANT-7  VANT-8  VANT-D  VANT-E  VANT-F  VANT-R  VBNT-A  VBNT-B  VBNT-L  VBNT-R in /etc/boards directory? What are they all for?

**Comment by LuKePicci** [comment]
Simply they kept board definitions for many models inside their buldtree

Inviato dal mio dispositivo Windows 10

Da: wuseman
Inviato: martedì 8 ottobre 2019 05:29
A: wuseman/TG799VAC-XTREME-17.2-MINT
Cc: Luca Piccirillo; Assign
Oggetto: Re: [wuseman/TG799VAC-XTREME-17.2-MINT] The Hack doesnt work (#9)

Is it default to have GBNT-G VANT-4 VANT-6 VANT-7 VANT-8 VANT-D VANT-E VANT-F VANT-R VBNT-A VBNT-B VBNT-L VBNT-R in /etc/boards directory? What are they all for?

**Comment by wuseman** [comment]
Okey, thanks for info.

I finally could fix a VANT-R version again, it is extremely slow compared to VBNT-W version.

Hope I will find a way to download a firmware to my VBNT-W box.

**Comment by LuKePicci** [comment]
Did  you try TFTP already?

Inviato dal mio dispositivo Windows 10

Da: wuseman
Inviato: martedì 8 ottobre 2019 11:57
A: wuseman/TG799VAC-XTREME-17.2-MINT
Cc: Luca Piccirillo; Assign
Oggetto: Re: [wuseman/TG799VAC-XTREME-17.2-MINT] The Hack doesnt work (#9)

Okey, thanks for info.
I finally could fix a VANT-R version again, it is extremely slow compared to VBNT-W version.
Hope I will find a way to download a firmware to my VBNT-W box.

**Comment by wuseman** [comment]
I still does not any firmware for VBNT-W wich is my "original", would it be possible to donload -W version from -R version you think?

**Comment by LuKePicci** [comment]
Wasn't it a VANT-W? If yes, I think you will find something interesting in the wiki. If it was a VBNT-W instead, I need exact firmware version as usual.

Inviato dal mio dispositivo Windows 10

Da: wuseman
Inviato: martedì 8 ottobre 2019 13:14
A: wuseman/TG799VAC-XTREME-17.2-MINT
Cc: Luca Piccirillo; Assign
Oggetto: Re: [wuseman/TG799VAC-XTREME-17.2-MINT] The Hack doesnt work (#9)

I still does not any firmware for VBNT-W wich is my "original", would it be possible to donload -W version from -R version you think?

**Comment by wuseman** [comment]
Oh, so you can create a firmware witrh only the firmware version, oh boy baby!

     Software Version
     17.2.0405-1441010-20181017112915
     VANT-W

**Comment by LuKePicci** [comment]
We have this already, look at the wiki https://hack-technicolor.readthedocs.io/en/stable/Firmware%20Repository/#tg799vac-xtream-vant-w

**Comment by wuseman** [comment]
I thought that was for antother version..

Awesome, I will try flash right ahead, I be back with result

**Comment by wuseman** [comment]
All resepect LukePicci!

It works as expected, thanks alot for your help, so this topic can be closed now I guess since it works fine to downgrade this version and then get root via the old method!

Cheers

**Comment by wuseman** [comment]
Where is the key stored?

**Comment by wuseman** [comment]
They have already upgraded my router while i wroted here, but they upgraded the router to: 17.2.0339-1441020-20180416103808 and not to the  17.2.0405-1441010-20181017112915, wounder why they didnt upgraded to the latest for me.

**Comment by LuKePicci** [comment]
Keep track of active bank. You were on bank_1 since you booted the firmware you loaded via TFTP. The upgrade was made to bank_2, so you're there now. Once you get root and OSCK, I suggest you immediately jump [here[(https://hack-technicolor.readthedocs.io/en/stable/Hack%20Type%201&2/#bank-planning-without-firmware-upgrade) and follow instructions for optimal bank plan and beyond as if you started reading the wiki from the index.. If you read the wiki from the index is the same, I'm assuming you already know the Type of firmware and how to get root, that's why I linked a guide step from the middle.

When you finished, [here](https://hack-technicolor.readthedocs.io/en/stable/Safe%20Firmware%20Upgrade/) you find instructions to upgrade keeping the root.

**Comment by LuKePicci** [comment]
For OSCK extraction, see https://github.com/pedro-n-rocha/secr
(yes, module for ECK extraction, eripv2 (mtd5) dump, then decrypt OSCK tag from eripv2 using ECK)

**Comment by wuseman** [comment]
I joining telegram again, im not very active but it's smoother to talk there.

Cheers! and thanks again

**Comment by LuKePicci** [comment]
ECK received, now waiting for your mtd5

**Comment by wuseman** [comment]
Yeah will give you this ASAP I will have access again, must setup a dhcp server for hack the router since, yeah you know my reset button is broken, got it broken when i tried to replace some components when i solder, i really trying to explore everything that is possible with this router, I was blocked from telia to get a new router but I will call them again later today maybe I can get a newer one to play with, I think they might have removed the block! :-) See ya soon with the MTD5 (I hope)

I think I can take the button from WPS and place it where reset button is and I should be able to use the reset button again :)

**Comment by wuseman** [comment]
btw @LuKePicci  do you know what clash is for? It seems Telia using this for connect to the router since they added their keys. I figured out how to add my own user under clash but when I join clash shell it's like a limited shell. So would be fun to know what this is used for if you know.

![Screenshot](https://i.ibb.co/89LnFjm/clash.png)
![Screenshot](https://i.ibb.co/8jmk4dV/clash20.png)

**Comment by LuKePicci** [comment]
Yes, it is a limited shell, but once you get in there it's easy to root via WPS button as we usually do for MST (no-brand) firmwares where SSH is available on LAN as well.

**Comment by raminmalek** [comment]
> > Ive got the white one. But mine is named 'V3' in the end. 'Telia WiFi-router Plus V3'
> 
> HAHA YOU GOT IT! let me update my previous summary
> 
> This is my small list of known Telia firmwares, those one marked with * are only supposed to be valid links as I have no more access to Telia network to get on my own.
> 
> ```
> http://131.116.22.230/15516436o1361004closed.rbi VDNT-O
> http://131.116.22.230/15516436o1361005closed.rbi VDNT-O
> 
> http://131.116.22.230/15516436r1361003closed.rbi VANT-R *
> http://131.116.22.230/1627732r2221004closed.rbi VANT-R
> http://131.116.22.230/172339r1021008closed.rbi	VANT-R
> http://131.116.22.230/172339r1021022closed.rbi	VANT-R
> 
> http://131.116.22.230/1627732w2221002closed.rbi VANT-W *
> http://131.116.22.230/172405w1441010closed.rbi	VANT-W *
> 
> http://131.116.22.230/172339h1441018closed.rbi VBNT-H
> http://131.116.22.230/172405h1441008closed.rbi VBNT-H *
> ```
> 
> > Btw, How do you downgrade?
> 
> Follow Type 3 instructions https://hack-technicolor.readthedocs.io/en/latest
> By 50% chances it will be damn easy, by the other 50% it will be quite difficult but **never impossible**.
> 
> > All 3 folders are empty, but there is no config directory for VANT-W
> 
> They are all part of the same family, now we only need to know if VANT-W really existed or it was just a leftover to show VANT-W in device details. The mistery above the second device of the list is still there
> 
> > I see radius passwords and secrets, what is this for?
> 
> It depends, usually you see such implementations for Community WiFi services or something else. Random data gets filled in by individual device eripv2 contents, so you arre probably seeing some default wpa2-enterprise passwords, as like as you see default wep and wpa2-personal passwords.

Do anyone have the firmware for VDNT-O (that is the "TG799vn v2" router)? The above mentioned links do not work anymore. :(

**Comment by raminmalek** [comment]
Also, I wanted to ask for your opinion on my issue. I have a TG799vn v2 router, but with a very old firmware (10.4.x), having an older GUI looking like this: http://i.imgur.com/Z0qv0uy.png

Since I am using this older version, I have had trouble getting root access for the router. For example, when I'm trying to use AutoFlashGUI, it does not work because the firmware does not use SRPv6 as authentication method. Also, I don't seem to manage to use the Ping & Traceroute method described in this guide since that option does not exist in my older GUI.:
https://hack-technicolor.readthedocs.io/en/stable/Hack%20Type%201&2/#my-firmware-is-so-old-that-autoflashgui-cant-authenticate

I have two things I'd like to test out with this router of mine (which I do not yet have physical access to until christmas when I will visit my parents):
* First, I'd like to try BOOTP flashing. The drawback of this is that, as I understand, that the chance of it working is 50%. If it does not work, it means the wrong bank is beeing loaded which can be a bit of a hassle to deal with. Also, I'm wondering my "old configuration" could make a mess with the newer firmware. It's worth a shoot. Another problem, I don't seem to find the firmware for VDNT-O just right now, perhaps the VANT-R could work still since they're almost completely the same router? 

* Test the key (superuser key?) which Wuseman has shared on his tutorial. I know that on my TG784, username Telia would work with the password "stanisskohag", perhaps Wuseman's key will work on my router? Then I could manage to configure my router which most importantly is the VoIP settings. 

Do you have any idea or tip on how I can root/hack my router?
Best regards,
r4ll3

**Comment by LuKePicci** [comment]
You did quite a lor of questions! I have an answer for all of them but it would take me a little bit to write them all down.

Very briefly, except for the bootloader (bootp, banks, failboot, eripv2, etc...) everything changed after firmware versions 10.x, everything which is version 15.x or newer (I don't know about 11 to 14) is a completely different -OpenWrt based- OS, thus it is perfectly normal you didn't manage to root with tools designed for new Homeware versions.

I could probably also help you getting root access on the old v10 firmware but it would be not permanent as the legacy OS stored only a single proprietary configuration script (a file called user.ini) which is executed on every boot and get dumped on every "save changes" operation.

Depending on what you would like to achieve I could suggest different paths, and yes, I also have the firmware you requested released by Telia. Upgrading from 10.x to 15.x is doable with no drawbacks, the new and different OS will simply ignore the old stuff. The opposite is not so easy, unless you promptly make a backup of that old stuff.

About compatibility. First, since your board is VDNT-O nothing which is not signed for VDNT-O can boot. Second, I also have a VDNT-O here with me which is not from Telia. It is running v10 firmware and I got root access to it so I dumped all partitions and keys, however for some really strange reasons it looks like it is not compatible with Telia firmware images as keys I got don't work (can't decrypt) Telia binary firmwares.

My best-path recommendation. Exploit your v10 firmware up to having full write access to that user.ini file, edit it in such a way you unlock telnet administrator shell (which is not a root shell). From there, use a smart combo of duplicate, deletepassive and switchover commands in such a way you get the old v10 firmware (which is not the old stuff I was talking above) backed up into bank 2 (which is not that one you see in the second row as "passive" bank) and bank 1 set as active. Then use BOOTP to load the new v15 firmware into bank 1 (bootp always flashes bank 1 only). If the new firmware is ok and compatible it will just boot. Otherwise it will fail and load the good old firmware from bank 2 instead. In case you get into the new firmware, root it with Ping exploit (AutoFlashGUI might not work on so old firmwares with existing presets, you will probably need the updated version you can currently see in AFG pending PR on github) and immediately backup everything, especially all /overlay contents, the mtd4 partition containing the old v10 firmware, and the mtd5 partition containing the keys we need to decrypt VDNT-O firmwares (again, mine gave me apparently wrong keys, so I'm really interested in those one) then go on with hack-technicolor.readthedocs.io, read through and skip the initial parts you already did in some other way and complete the bank planning.

If you manage to reach the end, we will list VDNT-O in that repo as well. Keep me updated, preferably on telegram, same nick.

**Comment by raminmalek** [comment]
> You did quite a lor of questions! I have an answer for all of them but it would take me a little bit to write them all down.
> 
> Very briefly, except for the bootloader (bootp, banks, failboot, eripv2, etc...) everything changed after firmware versions 10.x, everything which is version 15.x or newer (I don't know about 11 to 14) is a completely different -OpenWrt based- OS, thus it is perfectly normal you didn't manage to root with tools designed for new Homeware versions.
> 
> I could probably also help you getting root access on the old v10 firmware but it would be not permanent as the legacy OS stored only a single proprietary configuration script (a file called user.ini) which is executed on every boot and get dumped on every "save changes" operation.
> 
> Depending on what you would like to achieve I could suggest different paths, and yes, I also have the firmware you requested released by Telia. Upgrading from 10.x to 15.x is doable with no drawbacks, the new and different OS will simply ignore the old stuff. The opposite is not so easy, unless you promptly make a backup of that old stuff.
> 
> About compatibility. First, since your board is VDNT-O nothing which is not signed for VDNT-O can boot. Second, I also have a VDNT-O here with me which is not from Telia. It is running v10 firmware and I got root access to it so I dumped all partitions and keys, however for some really strange reasons it looks like it is not compatible with Telia firmware images as keys I got don't work (can't decrypt) Telia binary firmwares.
> 
> My best-path recommendation. Exploit your v10 firmware up to having full write access to that user.ini file, edit it in such a way you unlock telnet administrator shell (which is not a root shell). From there, use a smart combo of duplicate, deletepassive and switchover commands in such a way you get the old v10 firmware (which is not the old stuff I was talking above) backed up into bank 2 (which is not that one you see in the second row as "passive" bank) and bank 1 set as active. Then use BOOTP to load the new v15 firmware into bank 1 (bootp always flashes bank 1 only). If the new firmware is ok and compatible it will just boot. Otherwise it will fail and load the good old firmware from bank 2 instead. In case you get into the new firmware, root it with Ping exploit (AutoFlashGUI might not work on so old firmwares with existing presets, you will probably need the updated version you can currently see in AFG pending PR on github) and immediately backup everything, especially all /overlay contents, the mtd4 partition containing the old v10 firmware, and the mtd5 partition containing the keys we need to decrypt VDNT-O firmwares (again, mine gave me apparently wrong keys, so I'm really interested in those one) then go on with hack-technicolor.readthedocs.io, read through and skip the initial parts you already did in some other way and complete the bank planning.
> 
> If you manage to reach the end, we will list VDNT-O in that repo as well. Keep me updated, preferably on telegram, same nick.

Thank you for a very good reply! I think I understand what I have to do. The only thing that concerns me is the bit about exploiting my v10 firmware. I haven't found any way to get hold of the user.ini file. The telnet is obviously blocked, and the other tricks mentioned in this forum post: https://modem-help.board-directory.net/t1-fixing-username-password-problems when I last tried did not seem to work anymore (I guess the holes were covered when upgrading from v8 to v10). But as I said, I don't have physical access to the router yet so I will think about how to get to the user.ini file when I get back to my parents. If Wuseman's password works though, it obviously won't be a trouble (but shouldn't it be a low probability that Telia would use the same "SuperUser" password for v.10 as well as for the newer firmware that are OpenWRT based...).

If the above won't work, I'll have to try the BOOTP-flashing without switchover and hope that the active bank is already on configured for nr 1. The router is not of any value for us if it does not have VoIP activated so if it bricks, it won't matter that much. 

I'll be working with this as christmas arrives, then I'll contact you through Telegram for a follow up. :-) Would you mind sharing the VDNT-O-firmware? I understood that it's the only one that would work for a TG799vn v2 router

**Comment by LuKePicci** [comment]
The old v10 exploitation path goes through either symlink traversal via samba ext2/3 shares or built-in FTP media sharing service. From there, you should simply edit the existing default user role setting it to SuperUser and enable Telnet. That's all.

**Comment by Djo23** [comment]
Hi please I need help for tg799vn v2 lralia telecom I want unlock it

**Comment by wuseman** [comment]
> Hi please I need help for tg799vn v2 lralia telecom I want unlock it

Follow the wiki: https://hack-technicolor.readthedocs.io/
